### ISSUE TITLE
Consistency about test method declarations

### ISSUE THREAD

**Issue by peter279k** [bosunski/paystack#11]
As title, the `PHPUnit` provides two approaches about declaring test methods:

- Using the `test` prefix for method name. For example, `public function testMethodName`.
- Using the `@test` comment annotation to declare this methods.

And it seems that this repository has two approaches on this `test` folder.

After analyzing all test methods on `test` folder, the result is as follows:

Using the `@test` comment annotation has `115` times.

Using prefix-based for declaring `test` method has `25` times.

IMHO, I think it should be consistency and it can be easy for developers to know these methods belong to `PHPUnit` test methods.

Once this issue is accepted, I would be happy to work on this :).

**Comment by bosunski** [comment]
This is a wonderful observation 😀.  I'll be glad to see you work on it!

**Comment by peter279k** [comment]
Closed via PR #13.
